version: "3"

services:
  php:
    build: ./php
    depends_on:
      - sql
    env_file:
      - ./docker-compose.env
    ports:
      - 8081:80
    volumes:
      - ./php:/var/www/
  app:
    build: ./app
    depends_on:
      - php
    ports:
      - 8080:80
  sql:
    build: ./sql
    env_file:
      - ./docker-compose.env